import 'package:plezy/mpv/mpv.dart';

/// A [PlayerStreams] whose every stream is empty unless the caller names it.
///
/// Test-only. Production keeps all 18 required parameters required so that a
/// real player forgetting to publish a stream stays a compile error; a fake
/// that drives one or two streams should not have to respell the rest.
PlayerStreams emptyPlayerStreams({
  Stream<bool> playing = const Stream<bool>.empty(),
  Stream<bool> completed = const Stream<bool>.empty(),
  Stream<bool> buffering = const Stream<bool>.empty(),
  Stream<Duration> position = const Stream<Duration>.empty(),
  Stream<Duration?> playheadJump = const Stream<Duration?>.empty(),
  Stream<Duration> duration = const Stream<Duration>.empty(),
  Stream<bool> seekable = const Stream<bool>.empty(),
  Stream<Duration> buffer = const Stream<Duration>.empty(),
  Stream<double> volume = const Stream<double>.empty(),
  Stream<double> rate = const Stream<double>.empty(),
  Stream<Tracks> tracks = const Stream<Tracks>.empty(),
  Stream<TrackSelection> track = const Stream<TrackSelection>.empty(),
  Stream<PlayerLog> log = const Stream<PlayerLog>.empty(),
  Stream<PlayerError> error = const Stream<PlayerError>.empty(),
  Stream<AudioDevice> audioDevice = const Stream<AudioDevice>.empty(),
  Stream<List<AudioDevice>> audioDevices = const Stream<List<AudioDevice>>.empty(),
  Stream<void> playbackRestart = const Stream<void>.empty(),
  Stream<void> fileLoaded = const Stream<void>.empty(),
  Stream<void> fileStarted = const Stream<void>.empty(),
  Stream<void> fileLoadFailed = const Stream<void>.empty(),
  Stream<PlayerSourceStarted> sourceStarted = const Stream<PlayerSourceStarted>.empty(),
  Stream<PlayerSourceReady> sourceReady = const Stream<PlayerSourceReady>.empty(),
  Stream<PlayerSourceFailed> sourceFailed = const Stream<PlayerSourceFailed>.empty(),
  Stream<void> primaryMediaReady = const Stream<void>.empty(),
  Stream<void> hdrOutputChanged = const Stream<void>.empty(),
  Stream<List<BufferRange>> bufferRanges = const Stream<List<BufferRange>>.empty(),
  Stream<void> backendSwitched = const Stream<void>.empty(),
  Stream<String> trackTransition = const Stream<String>.empty(),
}) => PlayerStreams(
  playing: playing,
  completed: completed,
  buffering: buffering,
  position: position,
  playheadJump: playheadJump,
  duration: duration,
  seekable: seekable,
  buffer: buffer,
  volume: volume,
  rate: rate,
  tracks: tracks,
  track: track,
  log: log,
  error: error,
  audioDevice: audioDevice,
  audioDevices: audioDevices,
  playbackRestart: playbackRestart,
  fileLoaded: fileLoaded,
  fileStarted: fileStarted,
  fileLoadFailed: fileLoadFailed,
  sourceStarted: sourceStarted,
  sourceReady: sourceReady,
  sourceFailed: sourceFailed,
  primaryMediaReady: primaryMediaReady,
  hdrOutputChanged: hdrOutputChanged,
  bufferRanges: bufferRanges,
  backendSwitched: backendSwitched,
  trackTransition: trackTransition,
);
